import "./globals.css";
import { cookies } from 'next/headers'
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: "dclabs",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = await cookies();
  const token = cookieStore.get('admin_token')?.value;

  return (
    <html lang="ko">
      <head>
        <link 
          rel="stylesheet" 
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body className="layout">
        <main className="content">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}