import Login from './components/login';
import LogoutButton from './components/logoutBtn';
import "./globals.css";
import { cookies } from 'next/headers'

export const metadata = {
  title: "dclabs",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = await cookies();
  const token = cookieStore.get('admin_token')?.value;

  return (
    <html lang="ko">
      <body>
        <div>
          {token ? <LogoutButton/> : <Login/>}
        </div>
        {children}
      </body>
    </html>
  );
}